image: docker:latest

services:
  - docker:dind


stages:
  - test
  - build

before_script:
  - source ci/prepare


test_job:
  stage: test
  image: jfrutos/nodebuild:latest
  script:
    - npm install
    - npm run test

build_job:
  stage: build
  script:
    - docker info
    - docker_build_push $CI_BUILD_SHA
