FROM registry:2.6.2
MAINTAINER JAFB <jfrutos@gmail.com>

COPY ./registry/config.yml /etc/docker/registry/config.yml
COPY ./secrets/wildcard.crt /secrets/
COPY ./secrets/wildcard.key /secrets/
COPY ./registry/init /etc/docker/registry/init
