version: '2'

services:
  redis:
    #restart: always
    image: redis:4.0.6-alpine
    command:
    - --loglevel warning
    volumes:
    - redis:/var/lib/redis


  postgresql:
    #restart: always
    image: sameersbn/postgresql:9.6-2
    volumes:
    - postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm

  gitlab:
    #restart: always
    build:
      context: ./
      dockerfile: dockerfile-gitlab
    depends_on:
    - redis
    - postgresql
    volumes:
    - gitlab-data:/home/git/data
    - registry-data:/home/git/data/shared/registry
    - gitlab-logs:/var/log/gitlab
    environment:
    - DEBUG=false

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - TZ=Europe/Madrid
    - GITLAB_TIMEZONE=Madrid

    - GITLAB_HTTPS=true # <------

      ## REGISTRY
    - GITLAB_REGISTRY_ENABLED=true
    - GITLAB_REGISTRY_HOST=${REGISTRY_FQDN}
    - GITLAB_REGISTRY_PORT=443
    - GITLAB_REGISTRY_API_URL=http://registry:5000/
    - GITLAB_REGISTRY_KEY_PATH=/certs/wildcard.key
    - GITLAB_REGISTRY_ISSUER=${GITLAB_FQDN}

      ## SSL
    - SSL_SELF_SIGNED=true
    - SSL_CERTIFICATE_PATH=/certs/wildcard.crt
    - SSL_KEY_PATH=/certs/wildcard.key
    - SSL_VERIFY_CLIENT=off


    - GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN=${RUNNER_REGISTRATION_TOKEN} # <-------
    - GITLAB_HOST=${GITLAB_FQDN}
    - GITLAB_PORT=${GITLAB_PORT}
    - GITLAB_SSH_PORT=10022
    - GITLAB_RELATIVE_URL_ROOT=
    - GITLAB_SECRETS_DB_KEY_BASE=${DATABASE_PASSWORD} # <------
    - GITLAB_SECRETS_SECRET_KEY_BASE=${SECRET_KEY_BASE} # <------
    - GITLAB_SECRETS_OTP_KEY_BASE=${GITLAB_SECRETS_OTP_KEY_BASE} # <------

    - GITLAB_ROOT_PASSWORD=
    - GITLAB_ROOT_EMAIL=

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=notifications@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false

    - OAUTH_ENABLED=false
    - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=
    - OAUTH_ALLOW_SSO=
    - OAUTH_BLOCK_AUTO_CREATED_USERS=true
    - OAUTH_AUTO_LINK_LDAP_USER=false
    - OAUTH_AUTO_LINK_SAML_USER=false
    - OAUTH_EXTERNAL_PROVIDERS=

    - OAUTH_CAS3_LABEL=cas3
    - OAUTH_CAS3_SERVER=
    - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=false
    - OAUTH_CAS3_LOGIN_URL=/cas/login
    - OAUTH_CAS3_VALIDATE_URL=/cas/p3/serviceValidate
    - OAUTH_CAS3_LOGOUT_URL=/cas/logout

    - OAUTH_GOOGLE_API_KEY=
    - OAUTH_GOOGLE_APP_SECRET=
    - OAUTH_GOOGLE_RESTRICT_DOMAIN=

    - OAUTH_FACEBOOK_API_KEY=
    - OAUTH_FACEBOOK_APP_SECRET=

    - OAUTH_TWITTER_API_KEY=
    - OAUTH_TWITTER_APP_SECRET=

    - OAUTH_GITHUB_API_KEY=
    - OAUTH_GITHUB_APP_SECRET=
    - OAUTH_GITHUB_URL=
    - OAUTH_GITHUB_VERIFY_SSL=

    - OAUTH_GITLAB_API_KEY=
    - OAUTH_GITLAB_APP_SECRET=

    - OAUTH_BITBUCKET_API_KEY=
    - OAUTH_BITBUCKET_APP_SECRET=

    - OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL=
    - OAUTH_SAML_IDP_CERT_FINGERPRINT=
    - OAUTH_SAML_IDP_SSO_TARGET_URL=
    - OAUTH_SAML_ISSUER=
    - OAUTH_SAML_LABEL="Our SAML Provider"
    - OAUTH_SAML_NAME_IDENTIFIER_FORMAT=urn:oasis:names:tc:SAML:2.0:nameid-format:transient
    - OAUTH_SAML_GROUPS_ATTRIBUTE=
    - OAUTH_SAML_EXTERNAL_GROUPS=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME=
    - OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME=

    - OAUTH_CROWD_SERVER_URL=
    - OAUTH_CROWD_APP_NAME=
    - OAUTH_CROWD_APP_PASSWORD=

    - OAUTH_AUTH0_CLIENT_ID=
    - OAUTH_AUTH0_CLIENT_SECRET=
    - OAUTH_AUTH0_DOMAIN=

    - OAUTH_AZURE_API_KEY=
    - OAUTH_AZURE_API_SECRET=
    - OAUTH_AZURE_TENANT_ID=



  registry:
    build:
      context: ./
      dockerfile: dockerfile-registry
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      - REGISTRY_LOG_LEVEL=warning
      # Authentication
      - REGISTRY_AUTH_TOKEN_REALM=https://${GITLAB_FQDN}/jwt/auth
      - REGISTRY_AUTH_TOKEN_SERVICE=container_registry
      - REGISTRY_AUTH_TOKEN_ISSUER=${GITLAB_FQDN}
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/wildcard.crt
      - REGISTRY_STORAGE_DELETE_ENABLED=true

      # SSL
    #  - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/wildcard.crt
    #  - REGISTRY_HTTP_TLS_KEY=/certs/wildcard.key

    volumes:
      - registry-data:/var/lib/registry
    expose:
      - "5000"
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
  #  extra_hosts:
  #    - "registry.shl.com:${EXTERNAL_IP}"


  nginx:
    build:
      context: ./
      dockerfile: dockerfile-nginx
    ports:
      - 443:443
    links:
      - registry:registry
      - gitlab:gitlab


volumes:
  gitlab-data:
    driver: local
  gitlab-logs:
    driver: local
  postgresql:
    driver: local
  redis:
    driver: local
  registry-data:
    driver: local
  runner-data:
    driver: local
