FROM node:4.2.2
MAINTAINER JAFB <jfrutos@gmail.com>


COPY ./certs/wildcard.crt /etc/ssl/certs/wildcard.crt

RUN cat /etc/ssl/certs/wildcard.crt >>  /etc/ssl/certs/ca-certificates.crt

RUN update-ca-certificates


RUN git  config --global  http.sslCAInfo /etc/ssl/certs/wildcard.crt
