concurrent = 1
check_interval = 0


[[runners]]
  name = "ddd1893ece43"
  url = "http://gitlab"
  token = "dd454a3d6dad5a7ed3267d6f227fb3"
  executor = "docker"
  #pre_clone_script = "git  config --global  http.sslCAInfo /certs/wildcard.crt"
  pre_clone_script = "git config --global http.sslVerify false"
  [runners.docker]
    tls_verify = false
    image = "node:4.2.2"
    privileged = true
    disable_cache = false
    extra_hosts = ["gitlab.shl.com:192.168.0.10","registry.shl.com:192.168.0.10"]
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
